import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest';
import type { Server } from 'node:http';
import type { DatabaseSync } from 'node:sqlite';
import { spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  createWeaveServer,
  openDatabase,
  ProjectRepository,
  HookEventRepository,
  ClaudeCodeAdapter,
} from '@weave/server';
import { generateHookHandler } from '../init/helpers-gen';

vi.setConfig({ testTimeout: 20000 });

/**
 * Run the generated hook-handler.cjs as a child process, feeding it a stdin
 * payload. Uses async spawn (NOT execFileSync) so the daemon — which lives in
 * the parent process — keeps its event loop free to answer the child's POST.
 */
function runHandler(handlerPath: string, stdin: string, env: NodeJS.ProcessEnv): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [handlerPath], {
      env,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    child.stdin.on('error', () => {}); // child may exit before stdin drains
    child.stdin.write(stdin);
    child.stdin.end();
    child.stdout.on('data', () => {});
    child.stderr.on('data', () => {});
    child.on('error', reject);
    child.on('close', () => resolve());
  });
}

/**
 * End-to-end: a real `hook-handler.cjs` (generated by helpers-gen) runs as a
 * child process, reads a Claude Code hook payload from stdin, resolves the
 * project token + daemon port, and POSTs the report to a live daemon — which
 * normalizes and persists it. Verifies the full ingestion path lands a row.
 */
describe('hook-handler.cjs → daemon end-to-end', () => {
  let db: DatabaseSync;
  let server: Server;
  let port: number;
  let hookEvents: HookEventRepository;
  let projectId: number;
  let projectDir: string;
  let configRoot: string;
  let handlerPath: string;
  let savedAppdata: string | undefined;
  let savedXdg: string | undefined;

  beforeAll(async () => {
    // Isolate the daemon state dir so hook-handler.cjs reads our temp daemon.json
    // and never touches the real user config.
    configRoot = mkdtempSync(path.join(tmpdir(), 'weave-e2e-cfg-'));
    if (process.platform === 'win32') {
      savedAppdata = process.env.APPDATA;
      process.env.APPDATA = configRoot;
    } else {
      savedXdg = process.env.XDG_CONFIG_HOME;
      process.env.XDG_CONFIG_HOME = configRoot;
    }

    projectDir = mkdtempSync(path.join(tmpdir(), 'weave-e2e-proj-'));
    db = openDatabase(path.join(projectDir, 'weave.db'));
    const projects = new ProjectRepository(db);
    const row = projects.register({
      path: projectDir,
      name: 'e2e',
      token: 'e2e-token',
      source: 'init',
    });
    projectId = row.id;
    hookEvents = new HookEventRepository(db);
    server = createWeaveServer({
      projects,
      daemonToken: 'dtok',
      port: 0,
      hookEvents,
      adapters: [new ClaudeCodeAdapter()],
    });
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
    port = (server.address() as { port: number }).port;

    // Project token read by hook-handler.cjs (CLAUDE_PROJECT_DIR/.weave/token).
    mkdirSync(path.join(projectDir, '.weave'), { recursive: true });
    writeFileSync(path.join(projectDir, '.weave', 'token'), 'e2e-token');

    // Global daemon.json read by hook-handler.cjs (configDir/weave/daemon.json).
    mkdirSync(path.join(configRoot, 'weave'), { recursive: true });
    writeFileSync(
      path.join(configRoot, 'weave', 'daemon.json'),
      JSON.stringify({ pid: 0, port, token: 'dtok', startedAt: 'x' }),
    );

    // Generate the real hook handler into the project helpers dir.
    const helpersDir = path.join(projectDir, '.claude', 'helpers');
    mkdirSync(helpersDir, { recursive: true });
    handlerPath = path.join(helpersDir, 'hook-handler.cjs');
    writeFileSync(handlerPath, generateHookHandler());
  });

  afterAll(() => {
    server.close();
    db.close();
    rmSync(projectDir, { recursive: true, force: true });
    rmSync(configRoot, { recursive: true, force: true });
    if (process.platform === 'win32') {
      if (savedAppdata === undefined) delete process.env.APPDATA;
      else process.env.APPDATA = savedAppdata;
    } else {
      if (savedXdg === undefined) delete process.env.XDG_CONFIG_HOME;
      else process.env.XDG_CONFIG_HOME = savedXdg;
    }
  });

  it('forwards a Claude Code hook event into the daemon store', async () => {
    const hookStdin = JSON.stringify({
      hook_event_name: 'PostToolUse',
      session_id: 'e2e-sess',
      tool_name: 'Edit',
      tool_input: { file: 'a.ts' },
      tool_response: { ok: true },
      cwd: projectDir,
      transcript_path: path.join(projectDir, 't.jsonl'),
    });
    await runHandler(handlerPath, hookStdin, {
      ...process.env,
      CLAUDE_PROJECT_DIR: projectDir,
    });

    const rows = hookEvents.listByProject(projectId);
    expect(rows).toHaveLength(1);
    expect(rows[0].source).toBe('claude');
    expect(rows[0].eventType).toBe('PostToolUse');
    expect(rows[0].sessionId).toBe('e2e-sess');
    const norm = JSON.parse(rows[0].payload);
    expect(norm.toolName).toBe('Edit');
    expect(norm.toolInput).toEqual({ file: 'a.ts' });
  });

  it('exits 0 even when the daemon is unreachable', async () => {
    // Point the handler at a port nothing listens on — it must still exit 0
    // so it never blocks Claude Code.
    writeFileSync(
      path.join(configRoot, 'weave', 'daemon.json'),
      JSON.stringify({ pid: 0, port: 1, token: 'dtok', startedAt: 'x' }),
    );
    await expect(
      runHandler(
        handlerPath,
        JSON.stringify({ hook_event_name: 'PreToolUse' }),
        { ...process.env, CLAUDE_PROJECT_DIR: projectDir },
      ),
    ).resolves.toBeUndefined();
    // No new row was persisted (daemon unreachable).
    expect(hookEvents.listByProject(projectId)).toHaveLength(1);
  });
});
