export function generateHookHandler(): string {
  return `#!/usr/bin/env node
/**
 * weave hook-handler — forwards Claude Code hook events to the weave daemon.
 *
 * Reads the hook JSON from stdin, resolves the project token (.weave/token)
 * and daemon port (global weave/daemon.json), then POSTs a report to
 * http://127.0.0.1:<port>/hooks. Dependency-free and designed to NEVER block
 * Claude Code: every code path exits 0.
 * Generated by weave — do not edit manually.
 * @version weave@0.1.0
 */
'use strict';

const fs = require('fs');
const path = require('path');
const http = require('http');
const os = require('os');

const HOOK_TIMEOUT_MS = 5000;

// Ultimate safety net: never let this process outlive the hook window.
const GUARD = setTimeout(function () { process.exit(0); }, HOOK_TIMEOUT_MS);
GUARD.unref();

function configDir() {
  if (process.platform === 'win32') {
    return process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
  }
  if (process.platform === 'darwin') {
    return path.join(os.homedir(), 'Library', 'Application Support');
  }
  return process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
}

function readDaemonPort() {
  try {
    var statePath = path.join(configDir(), 'weave', 'daemon.json');
    var state = JSON.parse(fs.readFileSync(statePath, 'utf8'));
    return state && state.port ? state.port : null;
  } catch {
    return null;
  }
}

function readProjectToken(projectDir) {
  try {
    var tok = fs.readFileSync(path.join(projectDir, '.weave', 'token'), 'utf8').trim();
    return tok || null;
  } catch {
    return null;
  }
}

function readStdin() {
  return new Promise(function (resolve) {
    var data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', function (c) { data += c; });
    process.stdin.on('end', function () { resolve(data); });
    // Fallback if stdin never closes (e.g. manual invocation).
    setTimeout(function () { resolve(data); }, 500).unref();
  });
}

async function main() {
  var raw = await readStdin();
  var parsed = {};
  try { parsed = JSON.parse(raw); } catch {}

  var projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
  var token = readProjectToken(projectDir);
  var port = readDaemonPort();
  // Daemon not running or project not registered — fail silently.
  if (!token || !port) { process.exit(0); }

  var eventType = parsed.hook_event_name || parsed.event || 'unknown';
  var body = JSON.stringify({
    source: 'claude',
    eventType: eventType,
    sessionId: parsed.session_id || null,
    cwd: parsed.cwd || projectDir,
    payload: raw
  });

  var req = http.request({
    hostname: '127.0.0.1',
    port: port,
    path: '/hooks',
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'content-length': Buffer.byteLength(body),
      authorization: 'Bearer ' + token
    },
    timeout: HOOK_TIMEOUT_MS
  }, function () { process.exit(0); });
  req.on('error', function () { process.exit(0); });
  req.on('timeout', function () { req.destroy(); process.exit(0); });
  req.write(body);
  req.end();
}

main().catch(function () { process.exit(0); });
`;
}

export function generateStatusline(): string {
  return `#!/usr/bin/env node
/**
 * weave statusline
 * Outputs a one-line status summary.
 * Generated by weave — do not edit manually.
 * @version weave@0.1.0
 */
'use strict';
console.log('weave v0.1.0');
`;
}

export function generateAutoMemoryHook(): string {
  return `#!/usr/bin/env node
/**
 * weave auto-memory-hook
 * Triggered on UserPromptSubmit to record user context.
 * @version weave@0.1.0
 */
'use strict';

const chunks = [];
process.stdin.on('data', (c) => chunks.push(c));
process.stdin.on('end', () => {
  try {
    const input = JSON.parse(Buffer.concat(chunks).toString('utf-8'));
    process.stderr.write('[weave] auto-memory: session active\\n');
  } catch {
    // ignore
  }
  process.exit(0);
});
`;
}
