export function generateHookHandler(): string {
  return `#!/usr/bin/env node
/**
 * weave hook-handler
 * Reads hook event from stdin (JSON), processes, exits 0.
 * Generated by weave — do not edit manually.
 * @version weave@0.1.0
 */
'use strict';

const chunks = [];
process.stdin.on('data', (c) => chunks.push(c));
process.stdin.on('end', () => {
  try {
    const input = JSON.parse(Buffer.concat(chunks).toString('utf-8'));
    const eventType = input.hook_event_name || input.event || 'unknown';
    process.stderr.write('[weave] hook: ' + eventType + '\\n');
  } catch {
    // ignore malformed input
  }
  process.exit(0);
});
`;
}

export function generateStatusline(): string {
  return `#!/usr/bin/env node
/**
 * weave statusline
 * Outputs a one-line status summary.
 * Generated by weave — do not edit manually.
 * @version weave@0.1.0
 */
'use strict';
console.log('weave v0.1.0');
`;
}

export function generateAutoMemoryHook(): string {
  return `#!/usr/bin/env node
/**
 * weave auto-memory-hook
 * Triggered on UserPromptSubmit to record user context.
 * @version weave@0.1.0
 */
'use strict';

const chunks = [];
process.stdin.on('data', (c) => chunks.push(c));
process.stdin.on('end', () => {
  try {
    const input = JSON.parse(Buffer.concat(chunks).toString('utf-8'));
    process.stderr.write('[weave] auto-memory: session active\\n');
  } catch {
    // ignore
  }
  process.exit(0);
});
`;
}
