import type { InitComponents, HooksConfig, PlatformInfo } from '@weave/core';

export interface SettingsGeneratorInput {
  components: InitComponents;
  hooks: HooksConfig;
  platform: PlatformInfo;
  /** Absolute path to the helpers directory in the target project */
  helpersDir: string;
}

export function generateSettingsJson(input: SettingsGeneratorInput): Record<string, unknown> {
  const { components, hooks, platform, helpersDir } = input;

  const settings: Record<string, unknown> = {
    $comment: 'Generated by weave — do not edit manually',
  };

  // Hooks — only when both settings and helpers are enabled
  if (components.helpers) {
    const hookHandlerPath = platform.os === 'windows'
      ? `${helpersDir}/hook-handler.cjs`
      : helpersDir + '/hook-handler.cjs';

    const hooksConfig: Record<string, unknown>[] = [];

    if (hooks.preToolUse) {
      hooksConfig.push({
        matcher: 'PreToolUse',
        hooks: [{ type: 'command' as const, command: `node "${hookHandlerPath}"` }],
      });
    }
    if (hooks.postToolUse) {
      hooksConfig.push({
        matcher: 'PostToolUse',
        hooks: [{ type: 'command' as const, command: `node "${hookHandlerPath}"` }],
      });
    }
    if (hooks.userPromptSubmit) {
      hooksConfig.push({
        matcher: 'UserPromptSubmit',
        hooks: [{ type: 'command' as const, command: `node "${hookHandlerPath}"` }],
      });
    }
    if (hooks.sessionStart) {
      hooksConfig.push({
        matcher: 'SessionStart',
        hooks: [{ type: 'command' as const, command: `node "${hookHandlerPath}"` }],
      });
    }

    if (hooksConfig.length > 0) {
      const merged = hooksConfig.reduce<Record<string, unknown>>((acc, entry) => {
        const key = String(entry.matcher);
        acc[key] = (entry as Record<string, unknown>).hooks;
        return acc;
      }, {});
      settings['hooks'] = merged;
    }
  }

  // Permissions
  settings['permissions'] = {
    allow: ['Bash(npx weave:*)', 'Bash(pnpm:*)', 'Bash(npm:*)'],
    deny: ['Read(./.env)', 'Read(./.env.*)', 'Read(./secrets/*)'],
  };

  // Env
  settings['env'] = { WEAVE_ENABLED: 'true' };

  // Status line
  if (components.helpers) {
    settings['statusLine'] = {
      type: 'command' as const,
      command: platform.os === 'windows' ? `node "${helpersDir}/statusline.cjs"` : 'node ' + helpersDir + '/statusline.cjs',
    };
  }

  return settings;
}
