import type { StatuslineConfig, StatuslineNamedColor } from './config.js';
import {
  CONTEXT_STYLE_FORMAT,
  POWERLINE_DEFAULT_GLYPHS,
  SEGMENT_DEFAULT_FORMAT,
  SEGMENT_ORDER,
} from './config.js';
import { WEAVE_VERSION } from '../version.js';

/**
 * Generate the `helpers/statusline.cjs` source for a config.
 *
 * The config is embedded as a JSON literal so the script is self-contained —
 * changing the config regenerates the script (the watch service then observes
 * the `helpers/` write and pushes an SSE event). At runtime the script reads
 * Claude Code's statusline JSON from stdin and prints either a single line or a
 * multi-line summary, ANSI-coloured.
 *
 * Segments render in `config.lines` (draggable in the dashboard). A segment's
 * text is `icon? + label? + labelSeparator? + format(tokens)`, where `format`
 * defaults to the rendering the generator hard-coded before templates existed,
 * so an untouched config produces byte-identical output.
 *
 * Colours are either a named ANSI colour, an indexed 256 value (`ansi256:196`)
 * or truecolor hex (`#rrggbb`); unknown values degrade to white/none so a bad
 * config can never emit a malformed escape sequence.
 *
 * When `powerline.enabled`, segments render as solid background blocks joined
 * by Nerd-Font chevrons — a join glyph's fg is the previous block's bg and
 * its bg is the next block's, so consecutive blocks melt into one chevron
 * (ccstatusline's powerline bridge); a start/end cap frames the row. Each
 * segment can carry an icon and merge into the next block. `align` pads the
 * rendered line within the terminal width so it sits left, centred, or right.
 *
 * Runtime budget: Claude Code kills the command after 5s and re-runs it on a
 * ~300ms debounce, so every data path here is bounded — subprocesses carry a
 * 3s timeout and the transcript scan is incremental (see `sessionTokens`).
 */

/** Classic 16-colour foreground codes, keyed by the seven named colours. */
const ANSI: Record<StatuslineNamedColor, string> = {
  gray: '90',
  red: '31',
  green: '32',
  yellow: '33',
  blue: '34',
  magenta: '35',
  cyan: '36',
};

/** 16-colour background codes (bright black for gray). */
const BG: Record<StatuslineNamedColor, string> = {
  gray: '100',
  red: '41',
  green: '42',
  yellow: '43',
  blue: '44',
  magenta: '45',
  cyan: '46',
};

/** Legacy 10-cell progress bar (the `bar` config overrides these). */
const BAR_FILL = '█';
const BAR_EMPTY = '░';
const BAR_CELLS = 10;

/** Largest slice of transcript read in one render, to stay inside the 5s cap. */
const TRANSCRIPT_CHUNK = 8 * 1024 * 1024;

/** Distinct message ids retained in the transcript cache. */
const TRANSCRIPT_ID_CAP = 5000;

export function generateStatuslineScript(config: StatuslineConfig): string {
  const embeddedConfig = JSON.stringify(config);
  const embeddedAnsi = JSON.stringify(ANSI);
  const embeddedBg = JSON.stringify(BG);
  const embeddedFormats = JSON.stringify(SEGMENT_DEFAULT_FORMAT);
  const embeddedContextFormats = JSON.stringify(CONTEXT_STYLE_FORMAT);
  return `#!/usr/bin/env node
/**
 * weave statusline — generated by the weave dashboard.
 * Reads Claude Code's statusline JSON from stdin and prints a summary.
 * Generated by weave — do not edit manually.
 * @version weave@0.1.0
 */
'use strict';

const CONFIG = ${embeddedConfig};
const ANSI = ${embeddedAnsi};
const BG = ${embeddedBg};
const SEGMENT_FORMAT = ${embeddedFormats};
const CONTEXT_FORMAT = ${embeddedContextFormats};
const BAR_FILL = '${BAR_FILL}';
const BAR_EMPTY = '${BAR_EMPTY}';
const BAR_CELLS = ${BAR_CELLS};
// Stamped into the row-0 logo so the running version is always visible.
const WEAVE_VERSION = ${JSON.stringify(WEAVE_VERSION)};
// Powerline glyphs (Nerd Font), configurable via CONFIG.powerline: undefined
// falls back to the classic triangle set; an empty cap string disables the cap.
const PL = CONFIG.powerline || {};
const GLYPH_JOIN = PL.separator === undefined ? ${JSON.stringify(POWERLINE_DEFAULT_GLYPHS.separator)} : PL.separator;
const GLYPH_START = PL.startCap === undefined ? ${JSON.stringify(POWERLINE_DEFAULT_GLYPHS.startCap)} : PL.startCap;
const GLYPH_END = PL.endCap === undefined ? ${JSON.stringify(POWERLINE_DEFAULT_GLYPHS.endCap)} : PL.endCap;

// --- colour encoding -------------------------------------------------------
// A colour is a named ANSI colour ('red'), an indexed value ('ansi256:196') or
// truecolor hex ('#rrggbb' / '#rgb'). Anything unrecognised degrades to white
// (fg) or no background rather than emitting a broken escape sequence.

function hexToRgb(color) {
  var six = /^#([0-9a-fA-F]{6})$/.exec(color);
  if (six) {
    var s = six[1];
    return [parseInt(s.slice(0, 2), 16), parseInt(s.slice(2, 4), 16), parseInt(s.slice(4, 6), 16)];
  }
  var three = /^#([0-9a-fA-F]{3})$/.exec(color);
  if (three) {
    var t = three[1];
    return [parseInt(t[0] + t[0], 16), parseInt(t[1] + t[1], 16), parseInt(t[2] + t[2], 16)];
  }
  return null;
}

function indexed(color) {
  var m = /^ansi256:(\\d{1,3})$/.exec(color);
  if (!m) return null;
  var n = Number(m[1]);
  return n >= 0 && n <= 255 ? n : null;
}

function fgCode(color) {
  if (!color) return '39';
  if (ANSI[color]) return ANSI[color];
  var n = indexed(color);
  if (n !== null) return '38;5;' + n;
  var rgb = hexToRgb(color);
  if (rgb) return '38;2;' + rgb[0] + ';' + rgb[1] + ';' + rgb[2];
  return '37';
}

function bgCode(color) {
  if (!color) return null;
  if (BG[color]) return BG[color];
  var n = indexed(color);
  if (n !== null) return '48;5;' + n;
  var rgb = hexToRgb(color);
  if (rgb) return '48;2;' + rgb[0] + ';' + rgb[1] + ';' + rgb[2];
  return null;
}

function paint(text, color, bold, bg) {
  var fg = fgCode(color);
  var prefix = bold ? '1;' : '';
  var b = bgCode(bg);
  return '\\x1b[' + prefix + fg + (b ? ';' + b : '') + 'm' + text + '\\x1b[0m';
}

function dim(text) {
  return '\\x1b[2;90m' + text + '\\x1b[0m';
}

var input = {};
try { input = JSON.parse(require('fs').readFileSync(0, 'utf8')); } catch (e) {}

var cwd = (input.workspace && input.workspace.current_dir) || process.cwd();
var path = require('path');

// Normalise a used-percentage from Claude Code: value may be 0-100 or a 0-1 fraction.
function pctOf(value) {
  if (value == null || isNaN(value)) return null;
  var p = Number(value);
  if (p <= 1 && p > 0) p = p * 100;
  return Math.max(0, Math.min(100, Math.round(p)));
}

// Compact a token count: 1000000 -> '1.0M', 12000 -> '12k', 960900 -> '960.9k'.
// M keeps one decimal (matching how context windows are quoted); k drops a
// trailing '.0' so whole thousands read as '12k' rather than '12.0k'.
function humanize(n) {
  if (n == null || isNaN(n)) return '';
  var v = Number(n);
  if (v >= 1e6) return (v / 1e6).toFixed(1) + 'M';
  if (v >= 1e3) return (v / 1e3).toFixed(1).replace(/\\.0$/, '') + 'k';
  return String(Math.round(v));
}

// Render a progress bar of CONFIG.bar.cells cells from a 0-100 percentage.
function barFor(pct, bar) {
  var cells = Math.max(1, Math.min(40, (bar && bar.cells) || BAR_CELLS));
  var fill = (bar && bar.fill) || BAR_FILL;
  var empty = (bar && bar.empty) || BAR_EMPTY;
  var filled = Math.round((pct / 100) * cells);
  // A non-zero percentage must light at least one cell: with 12 cells even 4%
  // rounds down to 0 and the bar reads as completely empty next to "(4%)".
  if (pct > 0 && filled === 0) filled = 1;
  return new Array(filled + 1).join(fill) + new Array(cells - filled + 1).join(empty);
}

// Substitute {token} placeholders; an absent token renders as nothing rather
// than the string 'undefined'.
function applyFormat(tokens, format) {
  return String(format).replace(/\\{(\\w+)\\}/g, function (_m, key) {
    return tokens[key] === undefined || tokens[key] === null ? '' : String(tokens[key]);
  });
}

// --- data sources ----------------------------------------------------------

// Added/deleted line counts against HEAD. execFile (not exec) so no shell is
// involved — the old implementation shelled out to a cmd.exe-only 'find /c'
// that always failed on POSIX.
function parseNumstat(out) {
  var added = 0, deleted = 0, files = 0;
  var rows = out.split('\\n');
  for (var i = 0; i < rows.length; i++) {
    if (!rows[i]) continue;
    var p = rows[i].split('\\t');
    if (p.length < 3) continue;
    files++;
    // binary files report '-' instead of a line count
    if (p[0] !== '-') added += parseInt(p[0], 10) || 0;
    if (p[1] !== '-') deleted += parseInt(p[1], 10) || 0;
  }
  return { added: added, deleted: deleted, files: files };
}

function gitNumstat(dir) {
  var cp = require('child_process');
  var attempts = [
    ['--no-optional-locks', 'diff', 'HEAD', '--numstat'],
    ['--no-optional-locks', 'diff', '--numstat'],
  ];
  for (var i = 0; i < attempts.length; i++) {
    try {
      return parseNumstat(cp.execFileSync('git', attempts[i], {
        cwd: dir, stdio: ['ignore', 'pipe', 'ignore'], timeout: 3000, windowsHide: true,
      }).toString());
    } catch (e) { /* unborn HEAD, or not a repo — try the next form */ }
  }
  return null;
}

// Cumulative session tokens, read from the transcript Claude Code points us at.
//
// The scan is incremental: a small cache keyed by transcript path records how
// many bytes have been consumed and the running total, so steady-state renders
// read only the newly appended tail. The same assistant message is written once
// per content block (measured: 73 usage records for 26 distinct messages in one
// real session), so records are de-duplicated by message id — without that the
// total reads roughly three times too high.
function sessionTokens(transcriptPath) {
  if (!transcriptPath) return null;
  var fs = require('fs');
  var os = require('os');
  var crypto = require('crypto');
  var stat;
  try { stat = fs.statSync(transcriptPath); } catch (e) { return null; }
  if (!stat.size) return null;

  var key = crypto.createHash('sha1').update(transcriptPath).digest('hex').slice(0, 16);
  var cacheFile = path.join(os.tmpdir(), 'weave-sl-' + key + '.json');
  var cache = null;
  try { cache = JSON.parse(fs.readFileSync(cacheFile, 'utf8')); } catch (e) {}
  if (!cache || typeof cache.offset !== 'number' || typeof cache.total !== 'number' || !Array.isArray(cache.ids)) {
    cache = { offset: 0, total: 0, ids: [] };
  }
  // a shorter file means it was truncated or rewritten (/compact) — start over
  if (stat.size < cache.offset) cache = { offset: 0, total: 0, ids: [] };
  if (stat.size === cache.offset) return cache.total || null;

  var len = Math.min(stat.size - cache.offset, ${TRANSCRIPT_CHUNK});
  var buf = Buffer.alloc(len);
  var read = 0;
  var fd = -1;
  try {
    fd = fs.openSync(transcriptPath, 'r');
    read = fs.readSync(fd, buf, 0, len, cache.offset);
  } catch (e) {
    return cache.total || null;
  } finally {
    if (fd >= 0) { try { fs.closeSync(fd); } catch (e) {} }
  }

  var chunk = buf.slice(0, read).toString('utf8');
  var lastNewline = chunk.lastIndexOf('\\n');
  // no complete line yet (or the tail is mid-write) — leave it for the next run
  if (lastNewline < 0) return cache.total || null;
  var consumed = lastNewline + 1;

  var seen = {};
  for (var s = 0; s < cache.ids.length; s++) seen[cache.ids[s]] = true;
  var lines = chunk.slice(0, consumed).split('\\n');
  for (var i = 0; i < lines.length; i++) {
    if (!lines[i]) continue;
    var rec;
    try { rec = JSON.parse(lines[i]); } catch (e) { continue; }
    var msg = rec && rec.message;
    var usage = msg && msg.usage;
    if (!usage) continue;
    var id = msg.id || (rec && rec.uuid);
    if (!id || seen[id]) continue;
    seen[id] = true;
    cache.ids.push(id);
    cache.total += (usage.input_tokens || 0) + (usage.output_tokens || 0)
      + (usage.cache_read_input_tokens || 0) + (usage.cache_creation_input_tokens || 0);
  }
  cache.offset += consumed;
  if (cache.ids.length > ${TRANSCRIPT_ID_CAP}) {
    cache.ids = cache.ids.slice(cache.ids.length - ${TRANSCRIPT_ID_CAP});
  }
  try {
    // atomic replace: Claude Code can overlap renders, and a half-written
    // cache would silently corrupt the running total
    var tmp = cacheFile + '.' + process.pid + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify(cache));
    fs.renameSync(tmp, cacheFile);
  } catch (e) {}
  return cache.total || null;
}

// Tokens in the context window: prefer the component breakdown, then the
// session's input/output totals, then derive from the percentage.
function contextUsed(cw, total, pct) {
  var cu = cw.current_usage;
  if (cu) {
    var sum = (cu.input_tokens || 0) + (cu.output_tokens || 0)
      + (cu.cache_read_input_tokens || 0) + (cu.cache_creation_input_tokens || 0);
    if (sum > 0) return sum;
  }
  if (cw.total_input_tokens != null) {
    return cw.total_input_tokens + (cw.total_output_tokens || 0);
  }
  return Math.round((pct / 100) * (total || 0));
}

// Resolve a segment to its format tokens. null means "no data" — the segment is
// dropped from the line rather than rendering an empty shell.
function segmentTokens(key, seg) {
  switch (key) {
    case 'project': {
      // {name} is the directory basename, {path} the full working directory —
      // the latter is what the reference layout shows.
      var name = path.basename(cwd);
      return cwd ? { name: name, path: cwd } : null;
    }
    case 'git':
      try {
        var branch = require('child_process').execFileSync(
          'git', ['rev-parse', '--abbrev-ref', 'HEAD'],
          { cwd: cwd, stdio: ['ignore', 'pipe', 'ignore'], timeout: 3000, windowsHide: true }
        ).toString().trim();
        return branch ? { branch: branch } : null;
      } catch (e) { return null; }
    case 'changes': {
      var diff = gitNumstat(cwd);
      if (!diff) return null;
      return { added: diff.added, deleted: diff.deleted, files: diff.files };
    }
    case 'model': {
      var model = (input.model && input.model.display_name) || '';
      return model ? { model: model } : null;
    }
    case 'thinking': {
      var level = (input.effort && input.effort.level)
        || (input.thinking && input.thinking.enabled && 'thinking');
      return level ? { level: level } : null;
    }
    case 'context': {
      var cw = input.context_window || {};
      var pct = pctOf(cw.used_percentage);
      if (pct == null) return null;
      var size = cw.context_window_size || 0;
      var remaining = pctOf(cw.remaining_percentage);
      return {
        bar: barFor(pct, CONFIG.bar),
        percent: pct,
        used: humanize(contextUsed(cw, size, pct)),
        total: humanize(size),
        remaining: remaining == null ? '' : remaining,
      };
    }
    case 'tokens': {
      var cw2 = input.context_window || {};
      if (seg && seg.metric === 'context') {
        var used = cw2.total_input_tokens != null
          ? cw2.total_input_tokens + (cw2.total_output_tokens || 0)
          : (input.usage && input.usage.input_tokens != null ? input.usage.input_tokens : null);
        if (used == null) return null;
        var p = pctOf(cw2.used_percentage);
        return { total: humanize(used), percent: p == null ? '' : p };
      }
      var session = sessionTokens(input.transcript_path);
      return session == null ? null : { total: humanize(session), percent: '' };
    }
    case 'cost': {
      var cost =
        (input.cost && input.cost.total_cost_usd) ||
        (input.session && input.session.cost_usd) ||
        input.total_cost_usd;
      return cost != null ? { cost: '$' + Number(cost).toFixed(2) } : null;
    }
    case 'rate': {
      var rl = input.rate_limits && input.rate_limits.five_hour;
      var rp = rl && pctOf(rl.used_percentage);
      if (rp == null) return null;
      return { percent: rp, limit: '5h', resets: rl.resets_at || '' };
    }
    case 'time':
      return { time: new Date().toLocaleTimeString() };
    default:
      return null;
  }
}

// A segment's value template: an explicit format wins, then the legacy
// context.style field, then the built-in default that predates templates.
function formatFor(key, seg) {
  if (seg.format) return seg.format;
  if (key === 'context' && seg.style && CONTEXT_FORMAT[seg.style]) return CONTEXT_FORMAT[seg.style];
  return SEGMENT_FORMAT[key] || '{value}';
}

// Collect the enabled, non-empty segments in the row's order as render items.
// An item with merge:true joins the next non-merge block (shares its
// background) — the same convention ccstatusline uses for icon-then-label pairs.
function renderParts(keys) {
  var out = [];
  for (var i = 0; i < keys.length; i++) {
    var seg = CONFIG.segments[keys[i]];
    if (!seg || !seg.enabled) continue;
    var tokens = segmentTokens(keys[i], seg);
    if (!tokens) continue;
    var value = applyFormat(tokens, formatFor(keys[i], seg));
    if (value === '') continue;
    var label = seg.label
      ? seg.label + (CONFIG.labelSeparator == null ? ': ' : CONFIG.labelSeparator)
      : '';
    out.push({
      text: (seg.icon ? seg.icon + ' ' : '') + label + value,
      fg: seg.color,
      bold: seg.bold,
      bg: seg.backgroundColor,
      merge: !!seg.merge
    });
  }
  return out;
}

function renderLine(items) {
  var pending = [];
  var ordered = [];
  for (var i = 0; i < items.length; i++) {
    if (items[i].merge) { pending.push(items[i]); continue; }
    // the merge segments before this item join this block, sharing its bg —
    // they render flush against it (no separator of any kind)
    for (var m = 0; m < pending.length; m++) {
      pending[m].bg = items[i].bg;
      pending[m].joinsNext = true;
    }
    ordered = ordered.concat(pending);
    pending = [];
    ordered.push(items[i]);
  }
  // trailing merge segments have no following block; drop their background
  for (var j = 0; j < pending.length; j++) pending[j].bg = null;
  ordered = ordered.concat(pending);

  var isPower = !!(CONFIG.powerline && CONFIG.powerline.enabled);

  // Caps frame the run of backgrounded blocks. An item without a background
  // (the logo, or a segment whose bg was dropped) sits outside that run, so the
  // caps attach to the first/last block rather than to the row's extremes.
  var firstBg = -1;
  var lastBg = -1;
  for (var b = 0; b < ordered.length; b++) {
    if (ordered[b].bg) {
      if (firstBg < 0) firstBg = b;
      lastBg = b;
    }
  }

  var parts = [];
  var plainParts = [];
  for (var k = 0; k < ordered.length; k++) {
    var it = ordered[k];
    // a merge segment joins the item after it, so no separator goes between
    if (k > 0 && !ordered[k - 1].joinsNext) {
      var prev = ordered[k - 1];
      if (isPower && prev.bg && it.bg) {
        // powerline bridge (ccstatusline): the join glyph's fg is the previous
        // block's bg and its bg is the next block's, so the two blocks melt
        // into one chevron; when both blocks share a bg the glyph keeps the
        // previous block's fg so they read as a single block
        var bridgeFg = prev.bg === it.bg ? prev.fg : prev.bg;
        parts.push(paint(GLYPH_JOIN, bridgeFg, false, it.bg));
        plainParts.push(GLYPH_JOIN);
      } else if (isPower) {
        parts.push(' '); // a block without bg gets a plain gap, never a '│'
        plainParts.push(' ');
      } else {
        parts.push(CONFIG.separator);
        plainParts.push(CONFIG.separator);
      }
    }
    // an empty cap config ("" / disabled) skips that cap entirely
    if (isPower && k === firstBg && GLYPH_START) {
      parts.push(paint(GLYPH_START, it.bg, false, null));
      plainParts.push(GLYPH_START);
    }
    if (isPower) {
      parts.push(paint(' ' + it.text + ' ', it.fg, it.bold, it.bg));
      plainParts.push(' ' + it.text + ' ');
    } else {
      parts.push(paint(it.text, it.fg, it.bold, null));
      plainParts.push(it.text);
    }
    if (isPower && k === lastBg && GLYPH_END) {
      parts.push(paint(GLYPH_END, it.bg, false, null));
      plainParts.push(GLYPH_END);
    }
  }
  return { line: parts.join(''), plain: plainParts.join('') };
}

// Pad the line so it sits left / centre / right of the terminal width. The
// script runs as a subprocess, so it falls back to a sane default width. A
// small safety margin keeps the statusline clear of the terminal's right
// edge (ccstatusline reserves 6 columns for the same reason).
function alignLine(rendered) {
  if (CONFIG.align === 'left') return rendered.line;
  var cols =
    (input.terminal && (input.terminal.columns || input.terminal.width)) ||
    (process.stdout && process.stdout.columns) ||
    80;
  var usable = Math.max(20, cols - 6);
  var pad = 0;
  if (CONFIG.align === 'right') pad = Math.max(0, usable - rendered.plain.length - 2);
  else pad = Math.max(0, Math.floor((usable - rendered.plain.length) / 2));
  if (pad <= 0) return rendered.line;
  return new Array(pad + 1).join(' ') + rendered.line;
}

// The logo is always rendered — it identifies the statusline as weave's and
// carries the version that generated this script. Only its text/colour vary.
function logoItem() {
  return {
    text: CONFIG.logoText + ' v' + WEAVE_VERSION,
    fg: CONFIG.logoColor,
    bold: true,
    bg: null,
    merge: false
  };
}

// Ordered rows; each row is the left-to-right segment order. The logo prefixes
// row 0 only; rows are joined with a dim divider.
var rows = CONFIG.lines && CONFIG.lines.length ? CONFIG.lines : [${JSON.stringify(SEGMENT_ORDER)}];
var renderedLines = [];
for (var li = 0; li < rows.length; li++) {
  var items = renderParts(rows[li]);
  if (li === 0) items.unshift(logoItem());
  // lead each content line with a reset so Claude Code's dim setting for the
  // statusline area does not wash out our colours (ccstatusline does the same)
  renderedLines.push('\\x1b[0m' + alignLine(renderLine(items)));
  // the row divider is configurable and empty by default (the reference
  // layout stacks its rows with no rule between them)
  if (li < rows.length - 1 && CONFIG.divider) renderedLines.push(dim(CONFIG.divider));
}
process.stdout.write(renderedLines.join('\\n'));
`;
}
