import type { StatuslineColor, StatuslineConfig } from './config.js';
import { SEGMENT_ORDER } from './config.js';

/**
 * Generate the `helpers/statusline.cjs` source for a config.
 *
 * The config is embedded as a JSON literal so the script is self-contained —
 * changing the config regenerates the script (the watch service then observes
 * the `helpers/` write and pushes an SSE event). At runtime the script reads
 * Claude Code's statusline JSON from stdin and prints either a single line or a
 * two-line (header + divider + metrics) summary, ANSI-coloured.
 *
 * Segments render in `config.order` (draggable in the dashboard). Newer
 * segments map to Claude Code's stdin fields: `context_window.used_percentage`
 * (context bar), `rate_limits.five_hour.used_percentage` (rate), `effort.level`
 * (thinking), `git status --porcelain` (changes).
 *
 * When `powerline.enabled`, segments render as solid background blocks joined
 * edge-to-edge (ccstatusline-style); each segment can carry an icon and merge
 * into the next block. `align` pads the rendered line within the terminal
 * width so it sits left, centred, or right.
 */

const ANSI: Record<StatuslineColor, string> = {
  gray: '90',
  red: '31',
  green: '32',
  yellow: '33',
  blue: '34',
  magenta: '35',
  cyan: '36',
};

/** 16-colour background codes (bright black for gray). */
const BG: Record<StatuslineColor, string> = {
  gray: '100',
  red: '41',
  green: '42',
  yellow: '43',
  blue: '44',
  magenta: '45',
  cyan: '46',
};

/** Dim grey for the multi-layout divider line. */
const DIVIDER = '────────────────────────────────';

/** 10-cell progress bar glyphs (filled █ / empty ░). */
const BAR_FILL = '█';
const BAR_EMPTY = '░';
const BAR_CELLS = 10;

export function generateStatuslineScript(config: StatuslineConfig): string {
  const embeddedConfig = JSON.stringify(config);
  const embeddedAnsi = JSON.stringify(ANSI);
  const embeddedBg = JSON.stringify(BG);
  const embeddedDivider = JSON.stringify(DIVIDER);
  return `#!/usr/bin/env node
/**
 * weave statusline — generated by the weave dashboard.
 * Reads Claude Code's statusline JSON from stdin and prints a summary.
 * Generated by weave — do not edit manually.
 * @version weave@0.1.0
 */
'use strict';

const CONFIG = ${embeddedConfig};
const ANSI = ${embeddedAnsi};
const BG = ${embeddedBg};
const DIVIDER = ${embeddedDivider};
const BAR_FILL = '${BAR_FILL}';
const BAR_EMPTY = '${BAR_EMPTY}';
const BAR_CELLS = ${BAR_CELLS};

function paint(text, color, bold, bg) {
  var fg = ANSI[color] || '37';
  var prefix = bold ? '1;' : '';
  var bgCode = bg && BG[bg] ? ';' + BG[bg] : '';
  return '\\x1b[' + prefix + fg + bgCode + 'm' + text + '\\x1b[0m';
}

function dim(text) {
  return '\\x1b[2;90m' + text + '\\x1b[0m';
}

var input = {};
try { input = JSON.parse(require('fs').readFileSync(0, 'utf8')); } catch (e) {}

var cwd = (input.workspace && input.workspace.current_dir) || process.cwd();
var path = require('path');

// Normalise a used-percentage from Claude Code: value may be 0-100 or a 0-1 fraction.
function pctOf(value) {
  if (value == null || isNaN(value)) return null;
  var p = Number(value);
  if (p <= 1 && p > 0) p = p * 100;
  return Math.max(0, Math.min(100, Math.round(p)));
}

// Render a 10-cell progress bar from a 0-100 percentage.
function barFor(pct) {
  var filled = Math.round((pct / 100) * BAR_CELLS);
  return new Array(filled + 1).join(BAR_FILL) + new Array(BAR_CELLS - filled + 1).join(BAR_EMPTY);
}

// Resolve each segment to its visible text ('' when disabled/unavailable).
function segmentValue(key) {
  var seg = CONFIG.segments[key];
  if (!seg || !seg.enabled) return '';
  switch (key) {
    case 'project':
      return path.basename(cwd);
    case 'git':
      try {
        var branch = require('child_process').execSync(
          'git rev-parse --abbrev-ref HEAD',
          { cwd: cwd, stdio: ['ignore', 'pipe', 'ignore'], timeout: 3000 }
        ).toString().trim();
        return branch || '';
      } catch (e) { return ''; }
    case 'changes':
      try {
        var n = require('child_process').execSync(
          'git status --porcelain | find /c /v ""',
          { cwd: cwd, shell: true, stdio: ['ignore', 'pipe', 'ignore'], timeout: 3000 }
        ).toString().trim();
        return n ? String(n) : '';
      } catch (e) {
        try {
          var n2 = require('child_process').execSync(
            'git status --porcelain',
            { cwd: cwd, stdio: ['ignore', 'pipe', 'ignore'], timeout: 3000 }
          ).toString();
          var count = n2 ? n2.split('\\n').filter(function (l) { return l.length > 0; }).length : 0;
          return count ? String(count) : '';
        } catch (e2) { return ''; }
      }
    case 'model':
      return (input.model && input.model.display_name) || '';
    case 'thinking': {
      var level = (input.effort && input.effort.level) || (input.thinking && input.thinking.enabled && 'thinking');
      return level || '';
    }
    case 'context': {
      var pct = pctOf(input.context_window && input.context_window.used_percentage);
      if (pct == null) return '';
      var style = seg.style || 'both';
      if (style === 'bar') return barFor(pct);
      if (style === 'percent') return pct + '%';
      return pct + '% ' + barFor(pct);
    }
    case 'tokens': {
      var usage = input.usage || (input.context && input.context.usage);
      if (!usage) return '';
      var used = usage.input_tokens || usage.input || 0;
      return used ? Math.round(used / 1000) + 'k' : '';
    }
    case 'cost': {
      var cost =
        (input.cost && input.cost.total_cost_usd) ||
        (input.session && input.session.cost_usd) ||
        input.total_cost_usd;
      return cost != null ? '$' + Number(cost).toFixed(2) : '';
    }
    case 'rate': {
      var rl = input.rate_limits && input.rate_limits.five_hour;
      var rp = rl && pctOf(rl.used_percentage);
      return rp != null ? '5h ' + rp + '%' : '';
    }
    case 'time':
      return new Date().toLocaleTimeString();
    default:
      return '';
  }
}

// Collect the enabled, non-empty segments in config.order as render items. An
// item with merge:true joins the next non-merge block (shares its background) —
// the same convention ccstatusline uses for icon-then-label pairs.
function renderParts(keys) {
  var out = [];
  for (var i = 0; i < keys.length; i++) {
    var seg = CONFIG.segments[keys[i]];
    if (!seg || !seg.enabled) continue;
    var value = segmentValue(keys[i]);
    if (value === '') continue;
    out.push({
      text: (seg.icon ? seg.icon + ' ' : '') + value,
      fg: seg.color,
      bold: seg.bold,
      bg: seg.backgroundColor,
      merge: !!seg.merge
    });
  }
  return out;
}

function renderLine(items) {
  var pending = [];
  var ordered = [];
  for (var i = 0; i < items.length; i++) {
    if (items[i].merge) { pending.push(items[i]); continue; }
    // the merge segments before this item join this block, sharing its bg
    for (var m = 0; m < pending.length; m++) pending[m].bg = items[i].bg;
    ordered = ordered.concat(pending);
    pending = [];
    ordered.push(items[i]);
  }
  // trailing merge segments have no following block; drop their background
  for (var j = 0; j < pending.length; j++) pending[j].bg = null;
  ordered = ordered.concat(pending);

  var isPower = !!(CONFIG.powerline && CONFIG.powerline.enabled);
  var parts = [];
  var plainParts = [];
  for (var k = 0; k < ordered.length; k++) {
    var it = ordered[k];
    if (isPower) {
      parts.push(paint(' ' + it.text + ' ', it.fg, it.bold, it.bg));
      plainParts.push(' ' + it.text + ' ');
    } else {
      parts.push(paint(it.text, it.fg, it.bold, null));
      plainParts.push(it.text);
    }
  }
  var sep = isPower ? '' : CONFIG.separator;
  return { line: parts.join(sep), plain: plainParts.join(sep) };
}

// Pad the line so it sits left / centre / right of the terminal width. The
// script runs as a subprocess, so it falls back to a sane default width.
function alignLine(rendered) {
  if (CONFIG.align === 'left') return rendered.line;
  var cols =
    (input.terminal && (input.terminal.columns || input.terminal.width)) ||
    (process.stdout && process.stdout.columns) ||
    80;
  var pad = 0;
  if (CONFIG.align === 'right') pad = Math.max(0, cols - rendered.plain.length - 2);
  else pad = Math.max(0, Math.floor((cols - rendered.plain.length) / 2));
  if (pad <= 0) return rendered.line;
  return new Array(pad + 1).join(' ') + rendered.line;
}

function logoItem() {
  if (!CONFIG.showLogo) return null;
  return { text: CONFIG.logoText, fg: CONFIG.logoColor, bold: true, bg: null, merge: false };
}

// Ordered rows; each row is the left-to-right segment order. The logo prefixes
// row 0 only; rows are joined with a dim divider.
var rows = CONFIG.lines && CONFIG.lines.length ? CONFIG.lines : [${JSON.stringify(SEGMENT_ORDER)}];
var renderedLines = [];
for (var li = 0; li < rows.length; li++) {
  var items = renderParts(rows[li]);
  if (li === 0) {
    var logo = logoItem();
    if (logo) items.unshift(logo);
  }
  renderedLines.push(alignLine(renderLine(items)));
  if (li < rows.length - 1) renderedLines.push(dim(DIVIDER));
}
process.stdout.write(renderedLines.join('\\n'));
`;
}
